[project]
name = "cip-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ArchmagePsy", email = "SeaOfCodeSi@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.30.0",
    "cip-core",
    "fastapi>=0.115.12",
    "gitpython>=3.1.44",
    "grpcio>=1.71.0",
    "psycopg2-binary>=2.9.10",
    "redis>=6.1.0",
    "sqlalchemy>=2.0.41",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
cip-core = { workspace = true }

[dependency-groups]
dev = [
    "alembic>=1.16.1",
    "grpcio-tools>=1.71.0",
    "pytest>=8.3.5",
    "testcontainers>=4.10.0",
]
