[project]
name = "cip-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ArchmagePsy", email = "SeaOfCodeSi@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "cip-core",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
cip-core = { workspace = true }
