[project]
name = "cip-client"
version = "0.1.0"
description = "A simple CLI for cip"
readme = "README.md"
authors = [
    { name = "ArchmagePsy", email = "SeaOfCodeSi@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "cip-core",
    "fire>=0.7.0",
    "pydantic>=2.11.4",
    "pydantic-settings>=2.9.1",
    "requests>=2.32.3",
]

[project.scripts]
cip-client = "cip_client.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
cip-core = { workspace = true }
