# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cip_server.daemon import daemon_pb2 as daemon__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in daemon_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PipelineExecutorStub(object):
    """
    The pipeline execution daemon is a background process that orchestrates the execution of project pipelines by
    recieving requests through the PipelineExecutor service. The daemon manages a pool of processes that execute
    the pipelines in isolated processes and temporary directories.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecutePipeline = channel.unary_unary(
                '/daemon.PipelineExecutor/ExecutePipeline',
                request_serializer=daemon__pb2.PipelineExecutionRequest.SerializeToString,
                response_deserializer=daemon__pb2.PipelineExecutionResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/daemon.PipelineExecutor/HealthCheck',
                request_serializer=daemon__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=daemon__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class PipelineExecutorServicer(object):
    """
    The pipeline execution daemon is a background process that orchestrates the execution of project pipelines by
    recieving requests through the PipelineExecutor service. The daemon manages a pool of processes that execute
    the pipelines in isolated processes and temporary directories.
    """

    def ExecutePipeline(self, request, context):
        """this method triggers the main body of work for the Pipeline Execuion Daemon
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """this method is used to check that the daemon is up and running 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PipelineExecutorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecutePipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecutePipeline,
                    request_deserializer=daemon__pb2.PipelineExecutionRequest.FromString,
                    response_serializer=daemon__pb2.PipelineExecutionResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=daemon__pb2.HealthCheckRequest.FromString,
                    response_serializer=daemon__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'daemon.PipelineExecutor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('daemon.PipelineExecutor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PipelineExecutor(object):
    """
    The pipeline execution daemon is a background process that orchestrates the execution of project pipelines by
    recieving requests through the PipelineExecutor service. The daemon manages a pool of processes that execute
    the pipelines in isolated processes and temporary directories.
    """

    @staticmethod
    def ExecutePipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.PipelineExecutor/ExecutePipeline',
            daemon__pb2.PipelineExecutionRequest.SerializeToString,
            daemon__pb2.PipelineExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.PipelineExecutor/HealthCheck',
            daemon__pb2.HealthCheckRequest.SerializeToString,
            daemon__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
