# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: daemon.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'daemon.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64\x61\x65mon.proto\x12\x06\x64\x61\x65mon\"@\n\x18PipelineExecutionRequest\x12\x0f\n\x07git_url\x18\x01 \x01(\t\x12\x13\n\x0b\x63ommit_hash\x18\x02 \x01(\t\":\n\x19PipelineExecutionResponse\x12\x1d\n\x15pipeline_execution_id\x18\x01 \x01(\t\"\x14\n\x12HealthCheckRequest\"\x15\n\x13HealthCheckResponse2\xb2\x01\n\x10PipelineExecutor\x12V\n\x0f\x45xecutePipeline\x12 .daemon.PipelineExecutionRequest\x1a!.daemon.PipelineExecutionResponse\x12\x46\n\x0bHealthCheck\x12\x1a.daemon.HealthCheckRequest\x1a\x1b.daemon.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'daemon_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PIPELINEEXECUTIONREQUEST']._serialized_start=24
  _globals['_PIPELINEEXECUTIONREQUEST']._serialized_end=88
  _globals['_PIPELINEEXECUTIONRESPONSE']._serialized_start=90
  _globals['_PIPELINEEXECUTIONRESPONSE']._serialized_end=148
  _globals['_HEALTHCHECKREQUEST']._serialized_start=150
  _globals['_HEALTHCHECKREQUEST']._serialized_end=170
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=172
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=193
  _globals['_PIPELINEEXECUTOR']._serialized_start=196
  _globals['_PIPELINEEXECUTOR']._serialized_end=374
# @@protoc_insertion_point(module_scope)
